version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image : csi-mailer:latest
    restart: always
    env_file:
      - .env
    ports:
      - 8000:8000
    volumes:
      - .:/go/src/app
